---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Check if GitLab configuration file already exists.
  stat: path=/etc/gitlab/gitlab.rb
  register: gitlab_config_file

- name: Check if GitLab is already installed.
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file

# Install GitLab and its dependencies.
- name: Install GitLab dependencies.
  package:
    name: "{{ gitlab_dependencies }}"
    state: present

- name: Install GitLab dependencies (Debian).
  apt:
    name: gnupg2
    state: present
  when: ansible_os_family == 'Debian'

- name: Download GitLab repository installation script.
  get_url:
    url: "{{ gitlab_repository_installation_script_url }}"
    dest: /tmp/gitlab_install_repository.sh
    validate_certs: "{{ gitlab_download_validate_certs }}"
  when: not gitlab_file.stat.exists

- name: Install GitLab repository.
  command: bash /tmp/gitlab_install_repository.sh
  register: output
  when: not gitlab_file.stat.exists

- name: Define the Gitlab package name.
  set_fact:
    gitlab_package_name: "{{ gitlab_edition }}{{ gitlab_package_version_separator }}{{ gitlab_version }}"
  when: gitlab_version | default(false)

- name: Install GitLab
  package:
    name: "{{ gitlab_package_name | default(gitlab_edition) }}"
    state: present
  async: 300
  poll: 5
  when: not gitlab_file.stat.exists

# Start and configure GitLab. Sometimes the first run fails, but after that,
# restarts fix problems, so ignore failures on this run.
- name: Reconfigure GitLab (first run).
  command: >
    gitlab-ctl reconfigure
    creates=/var/opt/gitlab/bootstrapped
  failed_when: false

- name: Create GitLab SSL configuration folder.
  file:
    path: /etc/gitlab/ssl
    state: directory
    owner: root
    group: root
    mode: 0700
  when: gitlab_create_self_signed_cert | bool

- name: Create self-signed certificate.
  command: >
    openssl req -new -nodes -x509 -subj "{{ gitlab_self_signed_cert_subj }}"
    -days 3650 -keyout {{ gitlab_ssl_certificate_key }} -out {{ gitlab_ssl_certificate }} -extensions v3_ca
    creates={{ gitlab_ssl_certificate }}
  when: gitlab_create_self_signed_cert | bool

#- name: "Use custom certbot | if gitlab_use_custom_certbot: true"
#  include_role:
#    name: ansible-role-certbot
#  vars:
#    certbot_create_method: webroot
#    certbot_install_from_source: false
#    certbot_auto_renew: true
#    certbot_auto_renew_hour: '5'
#    certbot_auto_renew_minute: '50'
#    certbot_create_if_missing: true
#    certbot_script_redhat: certbot
#    certbot_webroot_path: '/var/opt/gitlab/nginx/www'
#    #certbot_advanced_params: '--deploy-hook /etc/update_cert_in_db.sh'
#    certbot_admin_email: "{{ gitlab_email_from }}"
#    certbot_certs:
#      - email: "{{ gitlab_email_from }}"
#        domains: "{{ gitlab_domain }}"
#    certbot_create_command_webroot: >-
#      certbot certonly --expand --noninteractive --agree-tos
#      -a webroot --webroot-path={{ certbot_webroot_path }} --email {{ gitlab_email_from }}
#      -d {{ gitlab_domain }}
#  when:
#    - gitlab_use_custom_certbot | default('false')

- name: Copy GitLab configuration file.
  template:
    src: "{{ gitlab_config_template }}"
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify: restart gitlab
